name: flutter_app_chat_last_version
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  firebase_auth: ^0.16.0
  cloud_firestore: ^0.13.5
  shared_preferences: ^0.5.7
  photo_view: ^0.10.2
  image_picker: ^0.6.7+11
  camera: ^0.5.8+7
  path_provider: ^1.6.18
  path: ^1.7.0
  charts_flutter: ^0.9.0
  firebase_storage: ^3.0.3
  firebase_messaging: 6.0.9
  firebase_core: ^0.4.0
  device_info: ^0.4.2+9
  firebase_analytics: any
  flutter_local_notifications: ^1.4.3
  google_nav_bar: ^2.0.0
  fab_circular_menu: ^1.0.0
  unicorndial: ^1.1.4
  progress_dialog: ^1.1.0+1
  bot_toast: ^3.0.5
  provider: ^4.3.2+3
  crypto: ^2.1.5
  google_maps_flutter: ^0.5.11+1
  geolocator: ^6.1.5
  flutter_polyline_points: ^0.2.1
  url_launcher: ^5.7.0
  cached_network_image: ^2.4.0
  lint: ^1.0.0
  sliding_sheet: ^0.3.7
  rating_dialog: ^1.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.8.0
flutter_icons:
  image_path: "images/iconApp.png"
  android: true
  ios: true



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - images/backgroud.jpg
     - images/logo app.png
     - images/iconApp.png
     - images/title.png
     - images/facebook.png
     - images/google.png
     - images/Avt_Default.jpg
     - images/changeImageGroup.png
     - sticker_packs/1/
     - sticker_packs/2/
     - sticker_packs/3/
     - sticker_packs/4/
     - sticker_packs/5/
     - sticker_packs/6/
     - sticker_packs/7/
     - sticker_packs/sticker_packs.json
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
